<style>
    #map {
        height: 400px;
        width: 100%;
    }
</style>

<div id="map"></div>

<script type="text/javascript">
    function initMap() {
        var uluru = {lat: 20.363, lng: 131.100};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 4,
            center: uluru
        });
        var marker = new google.maps.Marker({
            position: uluru,
            map: map
        });
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->getGoogleMapKey(); ?>&callback=initMap">
</script>