<style>
    .column {
        float: left;
        width: 50%;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }
</style>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view-remoteip">
            <?php echo $this->__('Remote IP during registration') ?>
        </h4>
    </div>
    <div class="row">
        <div class="column">
            <fieldset>
                <div>
                    <button id="update_ip_address" name="update_ip_address" title="Update IP Address" type="button" class="scalable">
                        <span>
                            <span>
                                <span>Update IP Address</span>
                            </span>
                        </span>
                    </button>
                </div>

                <div id="table-info-customerip">
                    <?php echo $this->getChildHtml('customerip-info-table'); ?>
                </div>
            </fieldset>
        </div>

        <div class="column">
            <?php echo $this->getChildHtml('customer-gmap'); ?>
        </div>
    </div>
</div>

<script type="text/javascript">
    Event.observe('update_ip_address', 'click', function(event) {
        const customerIP = new CustomerIP(
            '<?php echo $this->getAjaxUrl(); ?>',
            $('entity_id').getValue(),
            'update_ip_address'
        );

        customerIP.update();
    });

</script>