<?php
    print_r($this->getInfoData());

    die();

?>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-customer-view-remoteip">
            <?php echo $this->__('Remote IP during registration') ?>
        </h4>
    </div>
    <fieldset>
        <table cellspacing="2" class="box-left">
            <td>
                <strong><?php echo $this->__('Last Logged In:') ?></strong>
            </td>
            <td>
                <?php echo $this->getRegistrationIp(); ?>
            </td>
        </table>

        <?php echo $this->getChildHtml('customer-gmap'); ?>
    </fieldset>
</div>