<?php
/*
 * This file is part of the DK_CustomerIP package.
 *
 * (c) Dmitry Kazak <dmitry.kazak0@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<style>
    #map-customer-ip {
        height: 400px;
        width: 100%;
    }
</style>

<div id="map-customer-ip"></div>

<?php
    $coordinates = $this->getCoordinates();
?>

<script type="text/javascript">
    function initMap() {
        const uluru = {
          lat: <?=$coordinates['latitude']?>,
          lng: <?=$coordinates['longitude']?>
        };

        const map = new google.maps.Map(document.getElementById('map-customer-ip'), {
          zoom: 4,
          center: uluru
        });

        const marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=<?php echo $this->getGoogleMapKey(); ?>&callback=initMap">
</script>