<?php
/*
 * This file is part of the DK_CustomerIP package.
 *
 * (c) Dmitry Kazak <dmitry.kazak0@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
?>
<table cellspacing="2" class="box-left">
    <?php foreach ($this->getInfoData() as $title => $info): ?>
        <tr>
            <td>
                <strong><?= $this->__($title) ?>:</strong>
            </td>
            <td>
                <?= $this->__($info) ?>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
